# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cpu/cpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu || ORIG_REF_NAME==cpu} -quiet] -quiet

# IP: bd/cpu/ip/cpu_processing_system7_0_0/cpu_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_processing_system7_0_0 || ORIG_REF_NAME==cpu_processing_system7_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_axi_gpio_0_0/cpu_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_axi_gpio_0_0 || ORIG_REF_NAME==cpu_axi_gpio_0_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_ps7_0_axi_periph_0/cpu_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_ps7_0_axi_periph_0 || ORIG_REF_NAME==cpu_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_rst_ps7_0_100M_0/cpu_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_rst_ps7_0_100M_0 || ORIG_REF_NAME==cpu_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/cpu/ip/cpu_auto_pc_0/cpu_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cpu_auto_pc_0 || ORIG_REF_NAME==cpu_auto_pc_0} -quiet] -quiet

# XDC: bd/cpu/cpu_ooc.xdc
