# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraint.xdc

# Block Designs: bd/gpio_arr/gpio_arr.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_arr || ORIG_REF_NAME==gpio_arr} -quiet] -quiet

# IP: bd/gpio_arr/ip/gpio_arr_gpio_array_0_0/gpio_arr_gpio_array_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_arr_gpio_array_0_0 || ORIG_REF_NAME==gpio_arr_gpio_array_0_0} -quiet] -quiet

# IP: bd/gpio_arr/ip/gpio_arr_vio_0_1/gpio_arr_vio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpio_arr_vio_0_1 || ORIG_REF_NAME==gpio_arr_vio_0_1} -quiet] -quiet

# XDC: bd/gpio_arr/gpio_arr_ooc.xdc
