# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param tcl.collectionResultDisplayLimit 0
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/saverio/GPIO_ARRAY/gpio_array.cache/wt [current_project]
set_property parent.project_path /home/saverio/GPIO_ARRAY/gpio_array.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths /home/saverio/GPIO_ARRAY/GPIO_ARRAY.srcs/sources_1/new [current_project]
set_property ip_output_repo /home/saverio/GPIO_ARRAY/gpio_array.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/saverio/GPIO_ARRAY/gpio_array.srcs/sources_1/bd/gpio_arr/hdl/gpio_arr_wrapper.vhd
add_files /home/saverio/GPIO_ARRAY/gpio_array.srcs/sources_1/bd/gpio_arr/gpio_arr.bd
set_property used_in_implementation false [get_files -all /home/saverio/GPIO_ARRAY/gpio_array.srcs/sources_1/bd/gpio_arr/ip/gpio_arr_vio_0_1/gpio_arr_vio_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/saverio/GPIO_ARRAY/gpio_array.srcs/sources_1/bd/gpio_arr/ip/gpio_arr_vio_0_1/gpio_arr_vio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/saverio/GPIO_ARRAY/gpio_array.srcs/sources_1/bd/gpio_arr/gpio_arr_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/saverio/GPIO_ARRAY/gpio_array.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files /home/saverio/GPIO_ARRAY/gpio_array.srcs/constrs_1/new/constraint.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top gpio_arr_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef gpio_arr_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file gpio_arr_wrapper_utilization_synth.rpt -pb gpio_arr_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
