set_property IOSTANDARD LVCMOS33 [get_ports {outputs_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputs_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputs_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputs_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk_0]
set_property PACKAGE_PIN D18 [get_ports {outputs_0[3]}]
set_property PACKAGE_PIN G14 [get_ports {outputs_0[2]}]
set_property PACKAGE_PIN M15 [get_ports {outputs_0[1]}]
set_property PACKAGE_PIN M14 [get_ports {outputs_0[0]}]
set_property PACKAGE_PIN L16 [get_ports clk_0]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_0_IBUF]
