set_property IOSTANDARD LVCMOS33 [get_ports {data_i[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_i[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_i[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_i[0]}]
set_property PACKAGE_PIN T16 [get_ports {data_i[3]}]
set_property PACKAGE_PIN W13 [get_ports {data_i[2]}]
set_property PACKAGE_PIN P15 [get_ports {data_i[1]}]
set_property PACKAGE_PIN G15 [get_ports {data_i[0]}]
set_property PACKAGE_PIN D18 [get_ports {data_o[3]}]
set_property PACKAGE_PIN G14 [get_ports {data_o[2]}]
set_property PACKAGE_PIN M15 [get_ports {data_o[1]}]
set_property PACKAGE_PIN M14 [get_ports {data_o[0]}]
set_property PACKAGE_PIN Y16 [get_ports start]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 1000000000.000 -name synth_clk -waveform {0.000 5.000} -add [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports start]

set_property IOSTANDARD LVCMOS33 [get_ports {data_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data_o[0]}]

