# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/uart/uart.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart || ORIG_REF_NAME==uart} -quiet] -quiet

# IP: bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_processing_system7_0_0 || ORIG_REF_NAME==uart_processing_system7_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_ps7_0_axi_periph_0/uart_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_ps7_0_axi_periph_0 || ORIG_REF_NAME==uart_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/uart/ip/uart_rst_ps7_0_100M_0/uart_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_rst_ps7_0_100M_0 || ORIG_REF_NAME==uart_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/uart/ip/uart_uart_rec_trans_0_0/uart_uart_rec_trans_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_uart_rec_trans_0_0 || ORIG_REF_NAME==uart_uart_rec_trans_0_0} -quiet] -quiet

# IP: bd/uart/ip/uart_auto_pc_0/uart_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_auto_pc_0 || ORIG_REF_NAME==uart_auto_pc_0} -quiet] -quiet

# XDC: bd/uart/ip/uart_processing_system7_0_0/uart_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uart_processing_system7_0_0 || ORIG_REF_NAME==uart_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/uart/ip/uart_rst_ps7_0_100M_0/uart_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uart_rst_ps7_0_100M_0 || ORIG_REF_NAME==uart_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/uart/ip/uart_rst_ps7_0_100M_0/uart_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==uart_rst_ps7_0_100M_0 || ORIG_REF_NAME==uart_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/uart/ip/uart_auto_pc_0/uart_auto_pc_0_ooc.xdc

# XDC: bd/uart/uart_ooc.xdc
