# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/saverio/saverio/zybo/prova_zybo_os/prova_zybo_os.srcs/sources_1/bd/cpu/ip/cpu_processing_system7_0_0/cpu_processing_system7_0_0.xci
# IP: The module: 'cpu_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saverio/saverio/zybo/prova_zybo_os/prova_zybo_os.srcs/sources_1/bd/cpu/ip/cpu_processing_system7_0_0/cpu_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/saverio/saverio/zybo/prova_zybo_os/prova_zybo_os.srcs/sources_1/bd/cpu/ip/cpu_processing_system7_0_0/cpu_processing_system7_0_0.xci
# IP: The module: 'cpu_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/saverio/saverio/zybo/prova_zybo_os/prova_zybo_os.srcs/sources_1/bd/cpu/ip/cpu_processing_system7_0_0/cpu_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
