set_property SRC_FILE_INFO {cfile:/home/andrea/SE_workspace/UARTWithInterrupt/UARTWithInterrupt.srcs/constrs_1/new/constr.xdc rfile:../../../UARTWithInterrupt.srcs/constrs_1/new/constr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports interrupt_0]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports interrupt_0]
